FLAG_CODES = {
    "Original": "",
    "English": "GB",
    "Spanish": "ES",
    "Ukrainian": "UA",
    "French": "FR",
    "German": "DE",
    "Portuguese": "PT",
    "Bulgarian": "BG",
    "Estonian": "EE",
    "Finnish": "FI",
    "Czech": "CZ",
    "Danish": "DK",
    "Greek": "GR",
    "Hungarian": "HU",
    "Indonesian": "ID",
    "Italian": "IT",
    "Japanese": "JP",
    "Korean": "KR",
    "Latvian": "LV",
    "Lithuanian": "LT",
    "Norwegian": "NO",
    "Polish": "PL",
    "Dutch": "NL",
    "Turkish": "TR",
    "Romanian": "RO",
    "Russian": "RU",
    "Slovak": "SK",
    "Slovenian": "SI",
    "Chinese": "CN",
    "Swedish": "SE",
}

LANGUAGE_CODES = {
    "Original": "Original",
    "Detect": "Detect",
    "English": "EN-US",
    "Spanish": "ES",
    "Ukrainian": "UK",
    "French": "FR",
    "German": "DE",
    "Portuguese": "PT-PT",
    "Bulgarian": "BG",
    "Estonian": "ET",
    "Finnish": "FI",
    "Czech": "CS",
    "Danish": "DA",
    "Greek": "EL",
    "Indonesian": "ID",
    "Italian": "IT",
    "Japanese": "JA",
    "Korean": "KO",
    "Latvian": "LV",
    "Lithuanian": "LT",
    "Norwegian": "NB",
    "Polish": "PL",
    "Dutch": "NL",
    "Turkish": "TR",
    "Romanian": "RO",
    "Slovak": "SK",
    "Slovenian": "SL",
    "Chinese": "ZH",
    "Swedish": "SV",
}
BAR_STYLES = [
    "▁▂▃▄▅▆▇█",
    "⣀⣄⣤⣦⣶⣷⣿",
    "⣀⣄⣆⣇⣧⣷⣿",
    "○◔◐◕⬤",
    "□◱◧▣■",
    "□◱▨▩■",
    "□▨▩■",
    "□◱▥▦■",
    "░▒▓█",
    "░█",
    "⬜⬛",
    "▱▰",
    "▭◼",
    "▯▮",
    "◯⬤",
    "⚪⚫",
    "▏▎▍▌▋▊▉█",
]

FONTS = [
    "OpenSans-Bold",
    "Roboto-Medium",
    "TheBoldFont-Bold",
    "Benguiat-Bold",
    "TrebuchetMS-Bold",
    "JosefinSans-Bold",
    "Montserrat-Bold",
    "WorkSans-Bold",
]

TO_KEEP_WARM = True

PROGRESS_BAR_STYLE = 2

TELEGRAM_MESSAGE_LENGTH_LIMIT = 4096

BAR_WIDTH = 17
